/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as HighlightsSlugRouteImport } from './routes/highlights_.$slug'
import { Route as WorkSlugRouteImport } from './routes/work_.$slug'
import { Route as WritingSlugRouteImport } from './routes/writing_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsSlugRoute = HighlightsSlugRouteImport.update({
  id: '/highlights_/$slug',
  path: '/highlights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work_/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing_/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/highlights': typeof HighlightsRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/highlights/$slug': typeof HighlightsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/highlights': typeof HighlightsRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/highlights/$slug': typeof HighlightsSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/writing/$slug': typeof WritingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consulting': typeof ConsultingRoute
  '/highlights': typeof HighlightsRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/work': typeof WorkRoute
  '/writing': typeof WritingRoute
  '/highlights_/$slug': typeof HighlightsSlugRoute
  '/work_/$slug': typeof WorkSlugRoute
  '/writing_/$slug': typeof WritingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consulting'
    | '/highlights'
    | '/playground'
    | '/resources'
    | '/work'
    | '/writing'
    | '/highlights/$slug'
    | '/work/$slug'
    | '/writing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consulting'
    | '/highlights'
    | '/playground'
    | '/resources'
    | '/work'
    | '/writing'
    | '/highlights/$slug'
    | '/work/$slug'
    | '/writing/$slug'
  id:
    | '__root__'
    | '/'
    | '/consulting'
    | '/highlights'
    | '/playground'
    | '/resources'
    | '/work'
    | '/writing'
    | '/highlights_/$slug'
    | '/work_/$slug'
    | '/writing_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultingRoute: typeof ConsultingRoute
  HighlightsRoute: typeof HighlightsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResourcesRoute: typeof ResourcesRoute
  WorkRoute: typeof WorkRoute
  WritingRoute: typeof WritingRoute
  HighlightsSlugRoute: typeof HighlightsSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WritingSlugRoute: typeof WritingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights_/$slug': {
      id: '/highlights_/$slug'
      path: '/highlights/$slug'
      fullPath: '/highlights/$slug'
      preLoaderRoute: typeof HighlightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work_/$slug': {
      id: '/work_/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing_/$slug': {
      id: '/writing_/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultingRoute: ConsultingRoute,
  HighlightsRoute: HighlightsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResourcesRoute: ResourcesRoute,
  WorkRoute: WorkRoute,
  WritingRoute: WritingRoute,
  HighlightsSlugRoute: HighlightsSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  WritingSlugRoute: WritingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
